{% set version = "1.13.1" %}

package:
  name: ray-packages
  version: {{ version }}

source:
  git_url: https://github.com/ray-project/ray
  git_rev: {{ version }}
  patches:
    - patches/0002-Redis-deps-now-build-but-do-not-link.patch
    - patches/0003-Disable-making-non-core-entry-scripts.patch
    - patches/0004-Remove-all-dependencies-from-setup.py.patch
    - patches/0005-Ignore-warnings-in-event.cc-and-logging.cc.patch
    - patches/0006-Add-bazel-linkopts-libs.patch
    - patches/0009-Update-protobuf-to-3.19.1.patch    #[protobuf == "3.19.*"]


build:
  number: 2

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - {{ compiler('c') }}      # [ ppc_arch != "p10"]
    - {{ compiler('cxx') }}    # [ ppc_arch != "p10"]
    - bazel {{ bazel }}
    - cython {{ cython }}
    - curl
    - make
    - python {{ python }}

outputs:
  - name: ray-all
    requirements:
      host:
        - python {{ python }}
      run:
        - python
        - {{ pin_subpackage('ray-default', exact=True) }}
        - {{ pin_subpackage('ray-dashboard', exact=True) }}
        - {{ pin_subpackage('ray-k8s', exact=True) }}
        - {{ pin_subpackage('ray-data', exact=True) }}
        - {{ pin_subpackage('ray-rllib', exact=True) }}
        - {{ pin_subpackage('ray-serve', exact=True) }}
        - {{ pin_subpackage('ray-tune', exact=True) }}
    test:
      imports:
        # dummy test; actual tests are in subpackages
        - ray

  - name: ray-core
    script: build-core.sh  # [not win]
    script: build-core.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}     # [ ppc_arch != "p10"]
        - {{ compiler('cxx') }}   # [ ppc_arch != "p10"]
        - bazel {{ bazel }}
        - sysroot_linux-64 2.17  # [linux64]
        - curl
        - cython >=0.29.15
        - make
        - m2-bash  # [win]
        - python {{ python }}
      host:
        - python {{ python }}
        - pip
        - packaging
        # pickle5 needs to be here, otherwise setup.py tries
        # to install it and it fails on conda-forge Windows CI
        - pickle5  # [py<38]
      run:
        - python {{ python }}
        - aiosignal
        - attrs {{ attrs }}
        - click {{ click }}
        - colorama
        - filelock
        - frozenlist
        - grpcio {{ grpcio }}
        - msgpack-python >=1.0.0, <2.0.0
        - numpy {{ numpy }}
        - pickle5  # [py<38]
        - protobuf {{ protobuf }}
        - psutil {{ psutil }}
        - pyyaml {{ pyyaml }}
        - redis-py >=3.5.0
        - setproctitle =1.2.2
        - requests {{ requests }}
        - virtualenv

    test:
      imports:
        - ray
        - ray._raylet
        - ray.actor
        - ray.runtime_context
        - ray.state
        - ray.worker
      commands:
        - python -c "import ray; ray.init()"

  - name: ray-default
    requirements:
      host:
        - python {{ python }}
      run: 
        - python {{ python }}
        - {{ pin_subpackage('ray-core', exact=True) }}
        - aiohttp >=3.7
        - aiohttp-cors
        - aioredis <2
        - colorful
        # gpustat-0.6.0 has a dependency which does not exist on Windows;
        # skip it there until gpustat is fixed as it is optional
        - gpustat  # [not win]
        - jsonschema
        - requests {{ requests }}
        - opencensus
        - prometheus_client >=0.7.1,<0.14.0
        - requests {{ requests }}
        - smart_open
        - py-spy >=0.2.0

    test:
      imports:
        # ray-default is a convenience wrapper with no imports of its own
        - ray
        # init-code seemingly depends on platform or other ambient things;
        # the following doesn't get triggered in CI, but was a problem in
        # https://github.com/conda-forge/ray-packages-feedstock/issues/16
        - ray._private.metrics_agent

  - name: ray-dashboard
    build:
      script:
        - cd python/ray/dashboard/client
        - npm install
        - npm ci
        - npm run build
        # not sure why this seems to get copied on windows but not linux...
        - mkdir -p $SP_DIR/ray/dashboard/client             # [not win]
        - cp -R ./build $SP_DIR/ray/dashboard/client/build  # [not win]
    requirements:
      build:
        - nodejs
      host:
        - nodejs
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-default', exact=True) }}
        - typing-extensions {{ typing_extensions }}
    test:
      imports:
        - ray.dashboard
      commands:
        - python -c "import ray; ray.init(include_dashboard=True)"

  - name: ray-k8s
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-core', exact=True) }}
        - python-kubernetes
        - urllib3
    test:
      imports:
        # there doesn't appear to be a k8s module, not sure how to test this
        - ray

  - name: ray-data
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-core', exact=True) }}
        - pandas
        - pyarrow {{ arrow }}
        - fsspec
    test:
      imports:
        - ray.data

  - name: ray-rllib
    build:
      entry_points:
        - rllib = ray.rllib.scripts:cli
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-tune', exact=True) }}
        - dm-tree {{ dm_tree }}
        - gym
        - lz4
        - matplotlib !=3.4.3
        # scikit-image uses a deprecated import for pooch, causing rllib to fail on import
        # pinning pooch to <1.5 solves this issue for now
        - pooch <1.5
        - pyyaml {{ pyyaml }}
        - scikit-image
        - scipy {{ scipy }}
        - tensorflow-base {{ tensorflow }}
        - keras {{ keras }}
    test:
      imports:
        - ray.rllib
      commands:
        - rllib --help

  - name: ray-serve
    build:
      entry_points:
        - serve = ray.serve.scripts:cli
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-core', exact=True) }}
        - uvicorn
        - requests {{ requests }}
        - starlette {{ starlette }}
        - fastapi
        - aiorwlock
    test:
      imports:
        - ray.serve

  - name: ray-tune
    build:
      entry_points:
        - tune = ray.tune.scripts:cli
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-core', exact=True) }}
        - pandas
        - requests {{ requests }}
        - tabulate
        - tensorboardX >=1.9
    test:
      imports:
        - ray.tune

about:
  home: https://github.com/ray-project/ray
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - licenses/abseil-LICENSE.txt
    - licenses/antirez-redis-COPYING.txt
    - licenses/arrow-LICENSE.txt
    - licenses/boost-LICENSE_1_0.txt
    - licenses/boringssl-LICENSE.txt
    - licenses/deckarep-golang-set-LICENSE.txt
    - licenses/flatbuffers-LICENSE.txt
    - licenses/gabime-spdlog-LICENSE.txt
    - licenses/gflags-COPYING.txt
    - licenses/glog-COPYING.txt
    - licenses/go-logr-LICENSE.txt
    - licenses/googletest-LICENSE.txt
    - licenses/grpc-LICENSE.txt
    - licenses/msgpack-COPYING.txt
    - licenses/onsi-ginkgo-LICENSE.txt
    - licenses/onsi-gomega-LICENSE.txt
    - licenses/opencensus-LICENSE.txt
    - licenses/opencensus-proto-LICENSE.txt
    - licenses/prometheus-LICENSE.txt
    - licenses/redis-hiredis-COPYING.txt
    - licenses/tporadowski-redis-license.txt
    - licenses/zlib-LICENSE.txt
  summary: Ray is a fast and simple framework for building and running distributed applications.
  description: |
    Ray is a fast and simple framework for building and running
    distributed applications.
  doc_url: https://ray.readthedocs.io/
  dev_url: https://github.com/ray-project/ray

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
