{% set version = "2.35.0" %}

package:
  name: ray-packages
  version: {{ version }}

source:
  git_url: https://github.com/ray-project/ray
  git_rev: ray-{{ version }}
  patches:
    - patches/0001-patch_for_rules_python.patch   #[ppc64le]
    - patches/0002-patch-redis-for-ar-ranlib.patch
    - patches/0003-Disable-making-non-core-entry-scripts.patch
    - patches/0004-Remove-all-dependencies-from-setup.py.patch
    - patches/0005-Ignore-warnings-in-event.cc-and-logging.cc.patch
    - patches/0006-Add-bazel-linkopts-libs.patch
    - patches/0008-Fixed-compilation-error.patch
    - patches/0009-fixed-grpc-issue.patch          #[x86_64]
    - patches/0010-Use-rules_perl-which-is-fixed-for-ppc.patch
    - patches/0011-grpc-change-only.patch       #[ppc64le]
    - patches/0012-Fixed-boringssl-issue.patch  #[ppc64le]

build:
  number: 1

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - {{ compiler('c') }}      # [ ppc_arch != "p10"]
    - {{ compiler('cxx') }}    # [ ppc_arch != "p10"]

outputs:
  - name: ray-all
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - pydantic {{ pydantic }}
        - {{ pin_subpackage('ray-air', exact=True) }}
        - {{ pin_subpackage('ray-default', exact=True) }}
        - {{ pin_subpackage('ray-client', exact=True) }}
        - {{ pin_subpackage('ray-data', exact=True) }}
        - {{ pin_subpackage('ray-rllib', exact=True) }}
        - {{ pin_subpackage('ray-serve', exact=True) }}
        - {{ pin_subpackage('ray-tune', exact=True) }}
        - {{ pin_subpackage('ray-train', exact=True) }}
    test:
      imports:
        # dummy test; actual tests are in subpackages
        - ray

  - name: ray-core
    script: build-core.sh  # [not win]
    script: build-core.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}     # [ ppc_arch != "p10"]
        - {{ compiler('cxx') }}   # [ ppc_arch != "p10"]
        - bazel 6.5.0
        - sysroot_linux-64 2.17  # [linux64]
        - patchelf
        - colorama
        - curl
        - cython >=0.29.32
        - make
        - m2-bash  # [win]
        - psutil
        - python {{ python }}
        - setproctitle ==1.2.2
      host:
        - python {{ python }}
        - pip
        - packaging
        # pickle5 needs to be here, otherwise setup.py tries
        # to install it and it fails on conda-forge Windows CI
        - {{ cdt('java-11-openjdk-devel') }}  # [ppc64le or s390x]
        - openjdk {{ openjdk }}               # [x86_64]
      run:
        - python {{ python }}
        - aiohttp >=3.7
        - aiosignal
        - click {{ click }}
        - colorama
        - filelock
        - frozenlist
        - grpcio {{ grpcio }}
        - msgpack-python >=1.0.0
        - numpy {{ numpy }}
        - packaging
        - protobuf {{ protobuf }}
        - psutil {{ psutil }}
        - pyyaml {{ pyyaml }}
        - jsonschema
        - setproctitle ==1.2.2
        - requests {{ requests }}

    test:
      imports:
        - ray
        - ray._raylet
        - ray.actor
        - ray.runtime_context
        - ray._private.state
        - ray._private.worker
      commands:
        - python -c "import ray; ray.init(ignore_reinit_error=True, num_cpus=4)"

  - name: ray-air
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - fsspec {{ fsspec }}
        - {{ pin_subpackage('ray-data', exact=True) }}
        - {{ pin_subpackage('ray-serve', exact=True) }}
        - {{ pin_subpackage('ray-train', exact=True) }}
        - {{ pin_subpackage('ray-tune', exact=True) }}
    test:
      imports:
        - ray.air

  - name: ray-default
    script: build-default.sh  # [not win]
    requirements:
      build:
        - nodejs
      host:
        - nodejs
        - python {{ python }}
      run: 
        - python {{ python }}
        - {{ pin_subpackage('ray-core', exact=True) }}
        - aiohttp >=3.7
        - aiohttp-cors
        - colorful
        # gpustat-0.6.0 has a dependency which does not exist on Windows;
        # skip it there until gpustat is fixed as it is optional
        - gpustat # [not win]
        - jsonschema
        - opencensus
        - prometheus_client >=0.7.1
        - requests {{ requests }}
        - smart_open
        - py-spy >=0.2.0
        - pydantic {{ pydantic }}
        - typing-extensions {{ typing_extensions }}
        - virtualenv >=20.0.24,<20.21.1

    test:
      imports:
        # ray-default is a convenience wrapper with no imports of its own
        - ray
        # init-code seemingly depends on platform or other ambient things;
        # the following doesn't get triggered in CI, but was a problem in
        # https://github.com/conda-forge/ray-packages-feedstock/issues/16
        - ray.dashboard
      commands:
        - export LD_PRELOAD=$PREFIX/lib/libstdc++.so.6
        - python -c "import ray; ray.init(include_dashboard=True, ignore_reinit_error=True, num_cpus=4)"

  - name: ray-client
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-core', exact=True) }}
        - python-kubernetes
        - urllib3
    test:
      imports:
        # there doesn't appear to be a k8s module, not sure how to test this
        - ray

  - name: ray-data
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-core', exact=True) }}
        - pandas
        - numpy {{ numpy }}
        - pyarrow {{ arrow }}
        - fsspec {{ fsspec }}
    test:
      imports:
        - ray.data

  - name: ray-rllib
    build:
      entry_points:
        - rllib = ray.rllib.scripts:cli
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-tune', exact=True) }}
        - dm-tree {{ dm_tree }}
        - gymnasium ==0.28.1
        - lz4
        - pyyaml {{ pyyaml }}
        - scikit-image
        - scipy {{ scipy }}
        - tensorflow-base {{ tensorflow }}
        - keras {{ keras }}
        - rich
        - openblas {{ openblas }}
        - typer
        - ml_dtypes {{ ml_dtypes }}
    test:
      requires:
        - scipy {{ scipy }}
        - openblas {{ openblas }}
      imports:
        - ray.rllib
      commands:
        - rllib --help
        - python -c "import subprocess, os; os.environ['PYTHONIOENCODING']='utf-8'; subprocess.run(['rllib', '--help'], capture_output=True, check=True)"

  - name: ray-serve
    build:
      entry_points:
        - serve = ray.serve.scripts:cli
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-default', exact=True) }}
        - uvicorn
        - requests {{ requests }}
        - starlette ==0.36.2
        - fastapi ==0.109.1
        - aiorwlock
        - fsspec {{ fsspec }}
    test:
      imports:
        - ray.serve

  - name: ray-tune
    build:
      entry_points:
        - tune = ray.tune.scripts:cli
    requirements:
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - {{ pin_subpackage('ray-default', exact=True) }}
        - fsspec {{ fsspec }}
        - pandas
        - requests {{ requests }}
        - pyarrow {{ arrow }}
        - tensorboardX >=1.9
    test:
      imports:
        - ray.tune

  - name: ray-train
    requirements:
      host:
        - python
      run:
        - fsspec {{ fsspec }}
        - python
        - {{ pin_subpackage('ray-tune', exact=True) }}
    test:
      imports:
        - ray.train

about:
  home: https://github.com/ray-project/ray
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - licenses/abseil-LICENSE.txt
    - licenses/antirez-redis-COPYING.txt
    - licenses/arrow-LICENSE.txt
    - licenses/boost-LICENSE_1_0.txt
    - licenses/boringssl-LICENSE.txt
    - licenses/deckarep-golang-set-LICENSE.txt
    - licenses/flatbuffers-LICENSE.txt
    - licenses/gabime-spdlog-LICENSE.txt
    - licenses/gflags-COPYING.txt
    - licenses/glog-COPYING.txt
    - licenses/go-logr-LICENSE.txt
    - licenses/googletest-LICENSE.txt
    - licenses/grpc-LICENSE.txt
    - licenses/msgpack-COPYING.txt
    - licenses/onsi-ginkgo-LICENSE.txt
    - licenses/onsi-gomega-LICENSE.txt
    - licenses/opencensus-LICENSE.txt
    - licenses/opencensus-proto-LICENSE.txt
    - licenses/prometheus-LICENSE.txt
    - licenses/redis-hiredis-COPYING.txt
    - licenses/tporadowski-redis-license.txt
    - licenses/zlib-LICENSE.txt
  summary: Ray is a fast and simple framework for building and running distributed applications.
  description: |
    Ray is a fast and simple framework for building and running
    distributed applications.
  doc_url: https://ray.readthedocs.io/
  dev_url: https://github.com/ray-project/ray

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
